#!/usr/bin/env python3

def q1(sentence):
    '''
    Given a string of multiple words separated by single spaces,
    return a new string with the sentence reversed. The words
    themselves should remain as they are. For example, given
    'it is accepted as a masterpiece on strategy', the returned
    string should be 'strategy on masterpiece a as accepted is it'.
    '''
    rev = sentence.split(' ')
    rev[-1::-1]
    return ' '.join(rev)

def q2(n):
    '''
    Given a positive integer, return its string representation with
    commas seperating groups of 3 digits. For example, given 65535
    the returned string should be '65,535'.
    '''
    return '{:,}'.format(n)

def q3(lst0, lst1):
    '''
    Given two lists of integers, return a sorted list that contains
    all integers from both lists in descending order. For example,
    given [3,4,9] and [8,1,5] the returned list should be [9,8,5,4,3,1].
    The returned list may contain duplicates.
    '''
    combined_list = lst0 + lst1
    sorted_list = sorted(combined_list, reverse=True)
    return sorted_list

def q4(s1,s2,s3):
    '''
    Given 3 scores in the range [0-100] inclusive, return 'GO' if
    the average score is greater than 50. Otherwise return 'NOGO'.
    '''
    scores = s1 + s2 + s3
    total = sum(scores)
    average = total / len(scores)
    if average > 50:
        return 'GO'
    else:
        return 'NOGO'

def q5(integer, limit):
    '''
    Given an integer and limit, return a list of even multiples of the
    integer up to and including the limit. For example, if integer==3 and
    limit==30, the returned list should be [0,6,12,18,24,30]. Note, 0 is
    a multiple of any integer except 0 itself.
    '''
    multiples = []
    for i in range(0, limit + 1, integer):
        if i % 2 == 0:
            multiples.append(i)
    return multiples

def q6(file1, file2):
    '''
    Given two filenames, return a list whose elements consist of line numbers
    for which the two files differ. The first line is considered line 0.
    '''
    diff_lines = []
    with open(file1, 'r') as f1, open(file2, 'r') as f2:
        for line_num, (line1, line2) in enumerate(zip(f1, f2)):
            if line1.strip() != line2.strip():
                diff_lines.append(line_num)
    return diff_lines

def q7(lst):
    '''
    Return the first duplicate value in the given list.
    For example, if given [5,7,9,1,3,7,9,5], the returned value should
    be 7.
    '''
    seen = set()
    for num in lst:
        if num in seen:
            return num
        seen.add(num)
    return None  

def q8(sentence):
    '''
    Given a sentence as a string with words being separated by a single space,
    return the length of the shortest word.
    '''
  words = sentence.split()
  if not words:
    return 0
  shortest_word_length = len(words[0])
  for word in words[1:]:
    shortest_word_length = min(shortest_word_length, len(word))

  return shortest_word_length


def q9(string):
    '''
    Given an alphanumeric string, return the character whose ascii value
    is that of the integer represenation of all of the digits in the string
    concatenated in the order in which they appear. For example, given
    'hell9oworld7', the returned character should be 'a' which has
    the ascii value of 97.
    '''
  digits = ''.join(filter(str.isdigit, s))
    if digits:
        concatenated_number = int(digits)
        return chr(concatenated_number)
    else:
        return None

def q10(numbers):
    '''
    Given a list of positive integers sorted in ascending order, return
    the first non-consecutive value. If all values are consecutive, return
    None. For example, given [1,2,3,4,6,7], the returned value should be 6. 
    '''
    for i in range(1, len(numbers)):
        if numbers[i] != numbers[i - 1] + 1:
            return numbers[i]
    return None

